# Generated by Django 4.2.16 on 2024-10-02 05:34

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dn_or_ip', models.CharField(max_length=100)),
                ('sql_user', models.CharField(max_length=100)),
                ('sql_passwd', django_cryptography.fields.encrypt(models.CharField(max_length=100))),
                ('create_date', models.DateField()),
            ],
        ),
    ]
