# Generated by Django 4.2.16 on 2024-10-02 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sqlscope', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='server',
            old_name='create_date',
            new_name='creation_date',
        ),
    ]
