# Generated by Django 4.2.16 on 2024-10-04 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sqlscope', '0002_rename_create_date_server_creation_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Server_status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('up_or_down', models.BooleanField()),
                ('engine_version', models.CharField(max_length=200)),
                ('record_date', models.DateField()),
                ('fk_server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sqlscope.server')),
            ],
        ),
    ]
