# Generated by Django 4.2.16 on 2024-10-06 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sqlscope', '0003_server_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server_status',
            name='record_date',
            field=models.DateTimeField(),
        ),
    ]
