# Generated by Django 4.2.16 on 2024-10-06 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sqlscope', '0004_alter_server_status_record_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server_status',
            name='record_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
