# Generated by Django 4.2.16 on 2024-10-06 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sqlscope', '0007_server_status_replication_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server_status',
            name='replication_status',
            field=models.IntegerField(null=True),
        ),
    ]
