# Generated by Django 4.2.16 on 2024-10-09 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sqlscope', '0008_alter_server_status_replication_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Engine_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engine_type', models.CharField(max_length=100)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='server_status',
            options={'verbose_name': 'Server_status', 'verbose_name_plural': 'Server_status'},
        ),
        migrations.RenameField(
            model_name='server_status',
            old_name='record_date',
            new_name='creation_date',
        ),
        migrations.AlterField(
            model_name='server',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
