# Generated by Django 4.2.16 on 2024-10-09 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sqlscope', '0009_engine_type_alter_server_status_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='fk_engine_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sqlscope.engine_type'),
            preserve_default=False,
        ),
    ]
