# Generated by Django 4.2.16 on 2024-10-17 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("sqlscope", "0011_server_enabled"),
    ]

    operations = [
        migrations.CreateModel(
            name="Engine_parameter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("datadir", models.CharField(blank=True, max_length=200, null=True)),
                ("tmpdir", models.CharField(blank=True, max_length=200, null=True)),
                ("max_connections", models.IntegerField(null=True)),
                (
                    "innodb_data_file_path",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("innodb_open_files", models.IntegerField(null=True)),
                ("innodb_page_size", models.IntegerField(null=True)),
                ("innodb_read_only", models.BooleanField()),
                ("innodb_sort_buffer_size", models.IntegerField(null=True)),
                (
                    "innodb_temp_data_file_path",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("innodb_buffer_pool_size", models.IntegerField(null=True)),
                ("innodb_log_file_size", models.IntegerField(null=True)),
                (
                    "innodb_flush_method",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("query_cache_size", models.IntegerField(null=True)),
                ("max_allowed_packet", models.IntegerField(null=True)),
                (
                    "fk_server",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="sqlscope.server"
                    ),
                ),
            ],
        ),
    ]
