# Generated by Django 4.2.16 on 2024-10-21 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("sqlscope", "0012_engine_parameter"),
    ]

    operations = [
        migrations.CreateModel(
            name="Engine_user",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(blank=True, max_length=200, null=True)),
                ("host", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "fk_server",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="sqlscope.server"
                    ),
                ),
            ],
        ),
    ]
