# Generated by Django 4.2.16 on 2025-01-04 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sqlscope', '0014_engine_parameter_creation_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='fk_engine_type',
        ),
        migrations.AddField(
            model_name='server',
            name='engine_type',
            field=models.CharField(choices=[('MySQL', 'MySQL'), ('PostgreSQL', 'PostgreSQL')], default='MySQL', max_length=10),
        ),
        migrations.DeleteModel(
            name='Engine_type',
        ),
    ]
