# Generated by Django 4.2.16 on 2025-01-08 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sqlscope', '0015_remove_server_fk_engine_type_server_engine_type_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Engine_parameter',
            new_name='Engine_mysql_parameter',
        ),
        migrations.CreateModel(
            name='Engine_postgresql_parameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_directory', models.CharField(blank=True, max_length=200, null=True)),
                ('temp_buffers', models.CharField(blank=True, max_length=200, null=True)),
                ('max_connections', models.IntegerField(blank=True, null=True)),
                ('shared_buffers', models.CharField(blank=True, max_length=200, null=True)),
                ('work_mem', models.CharField(blank=True, max_length=200, null=True)),
                ('maintenance_work_mem', models.CharField(blank=True, max_length=200, null=True)),
                ('effective_cache_size', models.CharField(blank=True, max_length=200, null=True)),
                ('max_wal_size', models.CharField(blank=True, max_length=200, null=True)),
                ('checkpoint_timeout', models.CharField(blank=True, max_length=200, null=True)),
                ('default_statistics_target', models.IntegerField(blank=True, null=True)),
                ('random_page_cost', models.FloatField(blank=True, null=True)),
                ('effective_io_concurrency', models.IntegerField(blank=True, null=True)),
                ('max_worker_processes', models.IntegerField(blank=True, null=True)),
                ('max_parallel_workers', models.IntegerField(blank=True, null=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('fk_server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sqlscope.server')),
            ],
            options={
                'verbose_name': 'Engine_postgresql_parameter',
                'verbose_name_plural': 'Engine_postgresql_parameters',
            },
        ),
    ]
