# Generated by Django 4.2.16 on 2025-01-11 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sqlscope', '0016_rename_engine_parameter_engine_mysql_parameter_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Server_database',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('database_name', models.CharField(max_length=100)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('fk_server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sqlscope.server')),
            ],
        ),
    ]
